File restructure
TechPlus-UW/techplusuw-api pull request #64
Opened 2021-01-24 20:06 UTC by AndyKChen

Closes #58

2021-01-24 20:22 UTC, mahadzaryab1 requested changes

2021-01-24 20:22 UTC, mahadzaryab1 commented on .gitignore
> +techplusuw_api.egg-info
what's this for?

2021-01-24 20:22 UTC, mahadzaryab1 commented on setup.py
> +    description = "API for Tech+ Portal Backend",
Can you use make this description more descriptive using what's in the README? I think this might be used for swagger later.

2021-01-24 20:22 UTC, mahadzaryab1 commented on techplusuw_api/__init__.py
> +from techplusuw_api.services.database import database
can you run isort to sort the imports?

2021-01-24 20:22 UTC, mahadzaryab1 commented on techplusuw_api/__init__.py
> +                    view_func=mentorship_match_view, methods=['GET', 'POST'])
is there any way we can make this cleaner? maybe put it in a separate function/file? how is this handled in the documentation?

2021-01-24 20:49 UTC, AndyKChen commented on techplusuw_api/__init__.py
> +                    view_func=mentorship_match_view, methods=['GET', 'POST'])
From what I see in the docs, they do something similar. They use blueprints with function-based views tho. I think cleaning this section up could be apart of a different issue when we decide on function vs class-based views. If there's something you want to change now, I'm happy to look into it further.

2021-01-24 20:49 UTC, AndyKChen commented on .gitignore
> +techplusuw_api.egg-info
When you run `pip install -e .` it generates this file.

2021-01-24 23:18 UTC, mahadzaryab1 commented on techplusuw_api/__init__.py
> +                    view_func=mentorship_match_view, methods=['GET', 'POST'])
Sounds good!

2021-01-24 23:29 UTC, mahadzaryab1 requested changes
LGTM - could you just add the new instructions to run in the README?

2021-01-24 23:29 UTC, mahadzaryab1 commented on setup.py
> +    long_description = readme,
This is cool!

2021-01-26 00:16 UTC, mahadzaryab1 requested changes

2021-01-26 00:16 UTC, mahadzaryab1 commented on README.md
> +pip install -e . # install application as a package
don't we need to install from the requirements.txt?

2021-01-30 16:40 UTC, mahadzaryab1 requested changes
There was an error with the deployment which I fixed! Only thing left now is to fix the lining errors. Are you able to do this?

2021-01-30 19:31 UTC, mahadzaryab1 approved these changes

2021-01-30 19:36 UTC, merged