35 migrations
TechPlus-UW/techplusuw-api pull request #70
Opened 2021-02-07 19:00 UTC by noredeen-alzubi

2021-02-07 22:43 UTC, mahadzaryab1 requested changes
Great work @noredeen-alzubi - added in a couple of comments. I also had a question - when I run the migration, it creates an alembic_version table. Is this used to determine which migration(s) to run? Also, make sure to add closing keywords to close the issue.

2021-02-07 22:43 UTC, mahadzaryab1 commented on README.md
> +```
We don't need this in the README. This should just be communicated internally within our team.

2021-02-07 22:43 UTC, mahadzaryab1 commented on techplusuw_api/__init__.py
> +    migrate = Migrate(app, db)
linting errors

2021-02-07 22:43 UTC, mahadzaryab1 commented on README.md
> +```
Can you specify how to run this exact migration in Heroku as well?

2021-02-07 22:48 UTC, noredeen-alzubi commented
> Is this used to determine which migration(s) to run?
This table keeps track of our schema versions. Alembic uses it to figure out the difference between the most recent version and the one requested via migrations (to know what exactly to do).

2021-02-07 23:28 UTC, mahadzaryab1 approved these changes
LGTM!

2021-02-08 04:34 UTC, AndyKChen approved these changes
Awesome work Noor!

2021-02-08 12:22 UTC, merged