Add swagger documentation for api
TechPlus-UW/techplusuw-api pull request #83
Opened 2021-02-21 03:12 UTC by akhterare

2021-02-22 16:34 UTC, noredeen-alzubi commented on requirements.txt
> +flask_swagger_ui
When I ran `pip install -r requirements.txt`, these two packages weren't picked up and I had to install them manually. Did you run into the same issue on your machine?

This may just be an issue with my setup, but maybe you need to provide package versions?

2021-02-22 17:12 UTC, noredeen-alzubi approved these changes
Looks good! Just beware of differing hostnames. We might need to tune this when we get to deployment.

2021-02-22 21:57 UTC, AndyKChen commented on requirements.txt
> +flask_swagger_ui
@noredeen-alzubi It seems to have downloaded fine for me by simply running the `pip install -r requirements.txt`

2021-02-22 22:22 UTC, AndyKChen approved these changes
Good work! Run the linter as there are some minor linting errors coming up.

2021-02-27 15:47 UTC, mahadzaryab1 requested changes
Added a few comments - feel free to fix them and then re-request a review. Also, as @AndyKChen  mentioned - you'll need to run the linter as there are some linter warnings showing up.

2021-02-27 15:47 UTC, mahadzaryab1 commented on Pipfile
> +[[source]]
@akhterare - what is this file?

2021-02-27 15:47 UTC, mahadzaryab1 commented on techplusuw_api/resources/member.py
> +                  type: bool
this shows up as "unknown type" on the swagger documentation - it should be `boolean`.

2021-02-27 15:47 UTC, mahadzaryab1 commented on techplusuw_api/__init__.py
> +            'app_name': "tech-plus-uw-api"
Can you change this to `Tech+ UW API`. This is what shows up as the headline on the browser tab.

2021-02-27 15:47 UTC, mahadzaryab1 commented on techplusuw_api/resources/mentor.py
> +                 description: the group's name
This schema isn't relevant to us - I believe it's from the example.

2021-02-27 15:47 UTC, mahadzaryab1 commented on techplusuw_api/resources/member.py
> +              id: User
This should be the `member` schema I believe.

2021-02-27 15:47 UTC, mahadzaryab1 commented on techplusuw_api/resources/mentor.py
> +                        type: string
This is also a schema from the example - we don't need this.

2021-02-27 19:00 UTC, akhterare commented on Pipfile
> +[[source]]
I think I created that when I created my virtual environment - I'll make sure to remove it

2021-02-27 19:00 UTC, akhterare commented on techplusuw_api/resources/member.py
> +                  type: bool
Fixed!

2021-02-27 19:03 UTC, akhterare commented on techplusuw_api/resources/mentor.py
> +                        type: string
You're right. I actually think we spoke about me not filling in these fields in the scope of this PR, so I'm going to remove the schema/parameters altogether here.

2021-02-28 17:26 UTC, mahadzaryab1 approved these changes
Added a small comment - once you fix that feel free to go ahead and merge into master

2021-02-28 17:26 UTC, mahadzaryab1 commented on techplusuw_api/resources/member.py
> +                  type: bool
I still see the type as `bool` here.

2021-03-09 16:42 UTC, merged